### ISSUE TITLE
Unable to run data center example

### ISSUE THREAD

**Issue by jadali17** [scaleoutsystems/fedn#103]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [x] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [ ] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
Data center example isn't running due to the read_data file pointing to ../Data/train.csv which doesn't exist for the data center example. Not sure if this is a bug on my end somehow or just an unfinished test file.

**Environment:**
 - OS: [Windows]
 - Version: [10]
 - Browser [Mozilla]
 - Version [83.0]

**Reproduction Steps**
Simply following the documentation to run the test with just change to .env file:  EXAMPLE = data-center

**Expected behavior**
Data center example should run properly and be able to train.

**Error code**
client_5  | -- RUNNING TRAINING --
client_5  | Using TensorFlow backend.
client_5  | Traceback (most recent call last):
client_5  |   File "train.py", line 35, in <module>
client_5  |     model = train(model,'../data/train.csv')
client_5  |   File "train.py", line 21, in train
client_5  |     (x_train, y_train) = read_data(data)
client_5  |   File "/app/client/read_data.py", line 16, in read_data
client_5  |     data = pd.read_csv(filename, sep = ',',index_col=[0])
client_5  |   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
client_5  |     return _read(filepath_or_buffer, kwds)
client_5  |   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
client_5  |     parser = TextFileReader(fp_or_buf, **kwds)
client_5  |   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
client_5  |     self._make_engine(self.engine)
client_5  |   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
client_5  |     self._engine = CParserWrapper(self.f, **self.options)
client_5  |   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
client_5  |     self._reader = parsers.TextReader(src, **kwds)
client_5  |   File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
client_5  |   File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
client_5  | FileNotFoundError: [Errno 2] File ../data/train.csv does not exist: '../data/train.csv'

**Contact Details**
jadalidaoud@gmail.com

**Comment by morganekmefjord** [comment]
The large files are not part of regular git commits and hence will not be downloaded if you dont have git lfs.
- Install git lfs.
- make git lfs pull
