### ISSUE TITLE
Tensorflow: Could not load dynamic library 'libcuda.so.1

### ISSUE THREAD

**Issue by jadali17** [scaleoutsystems/fedn#105]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [x] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [ ] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
Running the federation process seems to instigate the error log below:
I suspect it could be due to the tensorflow gpu version running doesn't work well alongside fedN and conflict. The training process continues as normal without fault after this log is displayed.

**Environment:**
- OS: [windows]
- Version: [10]
- Browser [mozilla]
- Version [83.0]
- Tensorflow 2.3.1

**Reproduction Steps**
Run the mnist example in the documentation with tensorflow 2.3.1 installed

**Error log**
client_2  | 2020-12-07 21:02:12.975489: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
client_2  | 2020-12-07 21:02:12.975543: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
client_2  | 2020-12-07 21:02:12.975574: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (f00c4eace373): /proc/driver/nvidia/version does not exist
client_2  | 2020-12-07 21:02:12.975758: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: 
AVX2 FMA
client_2  | 2020-12-07 21:02:12.984561: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2592005000 Hz
client_2  | 2020-12-07 21:02:12.985607: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe608000b20 initialized for platform Host (this does not guarantee that 
XLA will be used). Devices:
client_2  | 2020-12-07 21:02:12.985674: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
client_2  | -- RUNNING TRAINING --

**Contact Details**
jadalidaoud@gmail.com

**Comment by morganekmefjord** [comment]
Please google how to enable cuda support when running tensorflow. This is not related to FEDn.
1. Check cuda capabilities of your hardware.
2. If you are running docker you likely need an nvidia patched version.
