### ISSUE TITLE
Sometimes validations are plotted in the wrong order

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/fedn#182]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [x] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
Sometimes the validation boxplot "folds upon itself" - validation are plotted in the wrong order on the x-axis. Probably there is a problem sorting the validations on timestamp or so. 

**Expected behavior**
A plot where all validation appears i chronological order. 

**Screenshots**
![image (12)](https://user-images.githubusercontent.com/2364390/115137555-0e5bd480-a027-11eb-936c-7acbe6664114.png)

**Contact Details**
An e-mail address in case we need to contact you for further details regarding this issue.

**Comment by ahellander** [comment]
This is fixed in develop.

**Comment by aitmlouk** [comment]
@ahellander solved maybe you need to close this issue

**Comment by ahellander** [comment]
Will be closed automatically when we merge in master next time.
