### ISSUE TITLE
Model upload error

### ISSUE THREAD

**Issue by sallogy** [scaleoutsystems/fedn#194]
**Severity**
- [x ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [ ] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [ ] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
When I try to upload  the mnist-keras or mnist-pytorch models at 'https://localhost:8090/control' , it gives a http 500 server error.
The log of the reducer contains the following error message:

model = self.load_model(path)
reducer_1  |   File "/app/fedn/fedn/utils/pytorchhelper.py", line 31, in load_model
reducer_1  |     b = np.load(path)
reducer_1  |   File "/usr/local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 457, in load
reducer_1  |     raise ValueError("Cannot load file containing pickled data "
reducer_1  | ValueError: Cannot load file containing pickled data when allow_pickle=False

It seems that numpy tries to load a pickled file with the allow_pickle=False option. 
This is for PyTorch, but the same error comes with the Keras model as well.

**Environment:**
 Ubuntu 18.04

**Contact Details**
gyorgy.sallo@qamcom.com

**Comment by ahellander** [comment]
Hi, is this a fresh clone of the repo, or is it possible that you have old versions of the seed files?

**Comment by sallogy** [comment]
Hi @ahellander, thanks for the quick reply. I cloned the repo on April 30, using the provided seed.npz files. The are no other apparent errors in the server logs. Have any idea what to try next? Could it be an incorrect path  problem?

**Comment by ahellander** [comment]
Hmm, when I test it looks like the seed.npz in the mnist-pytorch example is corrupted, but it works for me with the file in the keras version of the example. Are you sure you did not choose the version of the file from the torch example both times? 

We will do a hotfix for the torch example asap.

**Comment by ahellander** [comment]
Turned out that model upload worked fine, but error messages should be improved if trying to start a client when no seed file has been uploaded.
