### ISSUE TITLE
Upstream model consumption

### ISSUE THREAD

**Issue by morganekmefjord** [scaleoutsystems/fedn#222]
**Is your feature request related to a problem? Please describe.**
Allow upstream model consumption through direct integration.
(Replacing previous workflow-defined or manual flow of model )

**Describe the solution you'd like**
Implement integrated upstream model consumption
- Add model on round-complete through webhook.
- Assemble model entrypoint (as models can be dynamically typed we introduce a new entrypoint to assemble a model from any context) for upstream consumption.
- Reducer <-> deploy-context integration.

**Comment by ahellander** [comment]
Moving this to studio dev.
