### ISSUE TITLE
Multiple native clients not compatible with current log UI assuming port 8080 is allocatable.

### ISSUE THREAD

**Issue by morganekmefjord** [scaleoutsystems/fedn#234]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [x] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
When starting multiple clients on the same host machine running natively without config the default port is (obviously) in use for serving the client log UI. 

**Suggested mitigation**
 - Reverse the logic and disable the local UI by default and allow for parametric enabling of the local logging UI
 - We should update document about that also that exposing that endpoint you can relay also to any logging services your org might be using for aggregation of infra/service logs
 - Make configuration of port easier. 

**Furthermore**
- Also should we recover and try another port?

**Comment by ahellander** [comment]
I think the UI should be disabled by default (since we are not yet using it).

**Comment by ahellander** [comment]
Has been disabled now (but code is still there). Closing this, but we should later make a CLI flab to toggle it on/off.
