### ISSUE TITLE
Deprecated key & dynamic port warnings when starting minio service

### ISSUE THREAD

**Issue by tian-cthit** [scaleoutsystems/fedn#241]
**Severity**
Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
Got the following warnings when start the minio service. Version 0.2.4

minio_1          | WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
minio_1          |          Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
minio_1          | API: http://172.19.0.4:9000  http://127.0.0.1:9000 
minio_1          | 
minio_1          | Console: http://172.19.0.4:46547 http://127.0.0.1:46547 
minio_1          | 
minio_1          | Documentation: https://docs.min.io
minio_1          | 
minio_1          | WARNING: Console endpoint is listening on a dynamic port (46547), please use --console-address ":PORT" to choose a static port.

**Comment by ahellander** [comment]
@morganekmefjord tagged you here since you already have a fix pending in #240

**Comment by morganekmefjord** [comment]
Merged into develop.

**Comment by morganekmefjord** [comment]
Scheduled for inclusion in the next release.

**Comment by ahellander** [comment]
Now in master. Thanks @tian-cthit for bring this to our attention.
