### ISSUE TITLE
Upgrade mnist examples to work with  TF/Keras 2.6.0 

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/fedn#245]
**Is your feature request related to a problem? Please describe.**

In Tensorflow 2.6 there is no longer a "predict_classes", so validate.py in  test/mnist-keras is not working. 

**Describe the solution you'd like**
An overhaul of the client code to work with latest TF. 

**How would the solution positively affect the functionality?**

**Describe any drawbacks (if any)**
A clear and concise description of the negative outcomes of the suggested solution.

**Contact Details**
An e-mail address in case we need to contact you for further details regarding this request.

**Comment by rishawsingh** [comment]
@ahellander I want to work on this issue. Can you please help me on how I can?

**Comment by ahellander** [comment]
Given pending removal of test/ examples in main repo, the descibed updated should be done in this repo: https://github.com/scaleoutsystems/examples

**Comment by Wrede** [comment]
Pending PR [examples/pull#4](https://github.com/scaleoutsystems/examples/pull/4)

**Comment by Wrede** [comment]
the example now worj with tf v. >=2.3.2

**Comment by ahellander** [comment]
Done.
