### ISSUE TITLE
Update the mnist examples to handle data like the fraud and NLP examples

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/fedn#256]
**Is your feature request related to a problem? Please describe.**

The current MNIST examples reads the full dataset and subsamples a fraction of it. This should be removed, and instead we should have a script to partition the data in X clients (like in the fraud and NLP examples).

**Comment by Wrede** [comment]
Related PR pending [here](https://github.com/scaleoutsystems/examples/pull/6)

**Comment by Wrede** [comment]
PR above merged.
