### ISSUE TITLE
Improved visualization of FEDn network graph

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/fedn#266]
**Is your feature request related to a problem? Please describe.**

Is is often helpful to have a graphical representation of the FEDn network. We have a simple version now in the /network view, but this should be improved to better handle multiple combiners. Also, it would be nice if the actual client names/ids were shown, as well as their status (online/offline).

**Comment by aitmlouk** [comment]
It will be good also to make it more interactive, one can have more information about a client, collapse subgraph.

**Comment by ahellander** [comment]
Plotly network graph: https://plotly.com/python/network-graphs/

**Comment by Wrede** [comment]
Closing this issue, the mentioned features has been added. For more improvements on the graph create new issue.
