### ISSUE TITLE
fedn client --remote option broken 

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/fedn#276]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [x] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [ ] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
There is an option when starting the client to toggle fetching the remote exectution context (compute package) or use a local pre-staged version (useful for development of the package). 

  -r, --remote BOOLEAN            Enable remote configured execution context

Unfortunately, it appears broken: 

'fedn run client --remote=False' results in: 

 new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/andreas/github/scaleoutsystems/fedn/fedn/cli/run_cmd.py", line 75, in client_cmd
    client = Client(config)
  File "/Users/andreas/github/scaleoutsystems/fedn/fedn/fedn/client.py", line 120, in __init__
    copy_tree(from_path, run_path)
NameError: name 'run_path' is not defined

**Comment by morganekmefjord** [comment]
See PR #277

**Comment by ahellander** [comment]
Fix in develop. Will be in 0.2.6.
