### ISSUE TITLE
TF v2.6.1 requires grpcio >=v1.37.0

### ISSUE THREAD

**Issue by Wrede** [scaleoutsystems/fedn#302]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [x] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [ ] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
If a client have TF v2.6.1 causes conflicts with grpcio in fedn which uses v 1.34.0 

**Environment:**
 - OS: [e.g. mac OS]
 - Version: [e.g. macOS Catalina]

**Reproduction Steps**

**Expected behavior**

**Screenshots**

**Contact Details**
An e-mail address in case we need to contact you for further details regarding this issue.

**Comment by ahellander** [comment]
From 0.3.3 TF have been bumped, so this should not longer be an issue then. In develop now.
