### ISSUE TITLE
Combiner storage space issue/ model retention policies on the combiner

### ISSUE THREAD

**Issue by saadiabadi** [scaleoutsystems/fedn#321]
**Is your feature request related to a problem? Please describe.**
We are facing some problems with the FEDn in the combiner level where my combiners are running out of space because of the received model from all clients; those local models are saved in the Tmp file, which filled the combiner storage very fast, especially for large models and long-running experiment. for this reason, the combiner will be broken and the fedn network will not be available anymore. 

**Describe the solution you'd like**

What I would suggest is to have model retention policies on the combiner level to remove all of these saved models after combining them and the global partial model is extracted

**How would the solution positively affect the functionality?**
 This will improve the combiner efficiency and reduce the required resources for each combiner, also it will keep the fedn network functioning correctly for long- experiments and large models without any further storage space problem.

**Comment by ahellander** [comment]
@morganekmefjord I think this one would benefit from your input, before we implement any solution.

**Comment by ahellander** [comment]
There is a solution now in develop branch.

**Comment by ahellander** [comment]
In 0.5
