### ISSUE TITLE
InCorrect documentation

### ISSUE THREAD

**Issue by rai-prashanna** [scaleoutsystems/fedn#385]
I believe link to https://scaleoutsystems.github.io/fedn/deployment.html of "3. Deploy combiners" should be corrected to 
Copy ‘config/settings-combiner.yaml.template’ to ‘config/settings-combiner.yaml’ and edit it to provide a name for the......✅
instead of Copy ‘config/settings.yaml.template’ to ‘config/settings-combiner.yaml’ and edit it to provide a name for the.....❎

**Comment by Wrede** [comment]
Thank you for noticing this. While we are at it, the link to Examples should be updated.
