### ISSUE TITLE
broken link in documentation

### ISSUE THREAD

**Issue by rai-prashanna** [scaleoutsystems/fedn#386]
there is broken link to https://scaleoutsystems.github.io/fedn/deployment.html of  "4. Attach clients to the FEDn network" section
![image](https://user-images.githubusercontent.com/21035884/167082307-4017aa08-d6c1-409c-9e78-b934ed0fbdbf.png)

the hyperlink of Examples is not accessible.

**Comment by Wrede** [comment]
Thank you, will fix asap.

**Comment by ahellander** [comment]
Has this been fixed @Wrede ?

**Comment by Wrede** [comment]
No seems to have slipped away. Found more broken link in README.md "Documentation" both in text and the badge.
