### ISSUE TITLE
Expand support for async clients and straggler strategies   

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/fedn#429]
**Is your feature request related to a problem? Please describe.**

As a developer I want a structured process for experimenting with different strategies for handling stragglers, and I want to be able to experiment with more asynchronous client updates in a round.

**Comment by ahellander** [comment]
Progress on this in the draft PR.

**Comment by Wrede** [comment]
PR #437

**Comment by ahellander** [comment]
In develop branch, the support for stragglers and async control flows have been extended.

**Comment by ahellander** [comment]
Now in master.
