### ISSUE TITLE
TypeError TypeError: send_file() got an unexpected keyword argument 'attachment_filename'

### ISSUE THREAD

**Issue by aitmlouk** [scaleoutsystems/fedn#430]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [x] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [ ] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
Cannot download the config file (client.yaml) from UI

**Environment:**
 - OS: [Linux]
 - Version: [Ubuntu 20]

**Reproduction Steps**
1. Go to '/network'
2. Click on 'download client config'
4. See error 'TypeError TypeError: send_file() got an unexpected keyword argument 'attachment_filename'

**Expected behavior**
Download client.yaml

**Screenshots**

**Contact Details**
An e-mail address in case we need to contact you for further details regarding this issue.

**Comment by ahellander** [comment]
I can confirm this behavior (develop).

**Comment by ahellander** [comment]
This issue affects users on Python 3.10, it is due to an update in the Flask API. Fix in PR #435
