### ISSUE TITLE
Syntax error in Dockerfile

### ISSUE THREAD

**Issue by TheColdIce** [scaleoutsystems/fedn#679]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [ ] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [x] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
There is a syntax error in the Dockerfile. On line 44 it says `&& /venv/bin/pip install --no-cache-dir setuptools>=65 \`, but it should be `&& /venv/bin/pip install --no-cache-dir 'setuptools>=65' \` ?

**Comment by FrankJonasmoelle** [comment]
Good catch, thank you!
